### ISSUE TITLE
Is this repo still relevant?

### ISSUE THREAD

**Issue by elgalu** [aws-samples/aws-efa-eks#5]
The README states

> at the moment, eksctl doesnt have support to create EFA supported nodegroup

However this is no longer true:

```yaml
managedNodeGroups:
    instanceType: p4d.24xlarge
    efaEnabled: true
```

https://github.com/weaveworks/eksctl/pull/2688

or?
